const gabaritoDeDropagem={
    Q1:"lembra-te",
    Q2: "tambem",
    Q3: "doteu", 
    Q4: "criador",
    Q5: "nosdias",
    Q6: "datua",
    Q7: "mocidade",
    Q8: "antes",
    Q9: "que",
    Q10: "venham",
    Q11: "os",
    Q12: "maus",
    Q13: "dias",
    Q14: "e",
    Q15: "cheguem",
    Q16: "os2",
    Q17: "anos",
    Q18: "dos",
    Q19: "quais",
    Q20: "venhas",
    Q21: "dizer",
    Q22: "não",
    Q23: "tenho",
    Q24: "neles",
    Q25: "contentamento",
    Q26: "eclesiastes"
}