const gabaritoDeDropagem={
    Q1:"lembra-te",
    Q2: "tambem",
    Q3: "doteu", 
    Q4: "criador",
    Q5: "nosdias",
    Q6: "datua",
    Q7: "mocidade",
    Q8: "antes",
    Q9: "que",
    Q10: "venham",
    Q11: "os",
    Q12: "maus",
    Q13: "dias",
}